In [1]:
library(tidyverse)
library(cowplot)
library(latex2exp)
library(gggenes)
library(IRkernel)

base_dir = file.path("exp", "multiple_runs14")
dat_dir = file.path(base_dir, "data", "ins_del_analysis")
fig_dir = file.path(base_dir, "figs", "R01_INS_ESS_corr")
tmp_dir = file.path(base_dir, "tmp", "R01_INS_ESS_corr")

file_name_base = "20250204_"
run_id <- "multiple_runs14"

is_pos_df <- read_csv(file.path(dat_dir, paste0(file_name_base, "is_position_in_genome.csv")),comment = "#")
is_pos_df %>% head(2)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘cowplot’


The following object is masked from ‘package:lubridate’:

    stamp


Rows: 2385 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): IS_strand, Line
dbl (5): start, end, length, IS_id, Gen

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  start  end    IS_strand length IS_id Line  Gen
1 476928 480020 reverse   3093   0     L01-1 1
2 557167 560259 reverse   3093   1     L01-1 1

In [3]:
is_pos_df.sub <- is_pos_df %>% filter(end > 1400000, start < 2200000, Line == "L05-4")
is_pos_df.sub

   start   end     IS_strand length IS_id Line  Gen
1  1859371 1862461 reverse   3091    3    L05-4 1
2  1937769 1940860 forward   3092    4    L05-4 1
3  2061281 2064372 forward   3092    5    L05-4 1
4  1466007 1469098 reverse   3092    6    L05-4 2
5  1517757 1520848 reverse   3092    7    L05-4 2
6  1641279 1644371 reverse   3093    8    L05-4 2
7  1709698 1712790 reverse   3093    9    L05-4 2
8  1720277 1723369 forward   3093   10    L05-4 2
9  1791210 1794301 forward   3092   11    L05-4 2
10 1832799 1835891 forward   3093   12    L05-4 2
11 1874384 1877476 forward   3093   13    L05-4 2
12 1458016 1461108 forward   3093    8    L05-4 3
13 1594309 1597400 reverse   3092    9    L05-4 3
14 1604888 1607979 forward   3092   10    L05-4 3
15 1845481 1848571 reverse   3091   11    L05-4 3
16 1887065 1890156 reverse   3092   12    L05-4 3
17 1991236 1994326 reverse   3091   13    L05-4 3
18 2051836 2054927 reverse   3092   14    L05-4 3
19 2111972 2115063 forward   3092   15    L05-4 3
20 2132787 2135878 forward   3092   16    L05-4 3